# Data Cleaning and Feature Engineering

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('glassdoor_jobs.csv')

In [3]:
df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,Business Systems Analyst,$39K-$77K (Glassdoor est.),***This position is eligible for 100% work fro...,3.2,Healthesystems\n3.2,United States,"Tampa, FL",201 to 500 employees,2002,Company - Private,IT Services,Information Technology,$100 to $500 million (USD),"PMSI, myMatrixx"
1,Business Systems Analyst,$39K-$77K (Glassdoor est.),Client is seeking Business Systems analysts to...,4.5,Peterson Technology Partners\n4.5,"Northbrook, IL","Park Ridge, IL",201 to 500 employees,1997,Contract,Computer Hardware & Software,Information Technology,$25 to $50 million (USD),-1
2,Business Analyst,$39K-$77K (Glassdoor est.),Are you ready to be part of a mission that is ...,4.0,Pushpay\n4.0,"Redmond, WA","Redmond, WA",201 to 500 employees,2011,Company - Public,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,"Subsplash, Ministry Brands, Smartsheet"
3,Strategy & Analytics Analyst,$39K-$77K (Glassdoor est.),"Job Summary\nResponsible for researching, anal...",2.4,CSX\n2.4,"Jacksonville, FL","Jacksonville, FL",10000+ employees,1978,Company - Public,Transportation Management,Transportation & Logistics,$10+ billion (USD),"Union Pacific, BNSF Railway"
4,Business Systems Analyst,$39K-$77K (Glassdoor est.),MBC is a fast-growing firm that is seeking Bus...,3.7,Morgan Borszcz Consulting\n3.7,"Arlington, VA","Arlington, VA",51 to 200 employees,2003,Company - Private,Consulting,Business Services,$10 to $25 million (USD),-1

In [4]:
#Remove Salary Estimate = -1
df =df[ df['Salary Estimate'] != '-1']

### To do
- Salary Parsing
- Company name text only
- Location
- Age of company
- job desc parsing

## 1. Parsing Salary

In [27]:
salary = df['Salary Estimate'].apply(lambda x: x.split('(')[0])

#remove K and $ sign
salary = salary.apply(lambda x: x.replace('K','').replace('$',''))
salary.unique()

array(['39-77 ', '70-85', '76-90 ', '38-72 ', '32-64 ', '41-80 ',
       '34-67 ', '49-91 ', '46-87 ', '59-78 ', '51-94 ', '55-74 ',
       '62-77 ', '53-95 ', '61-63 ', '47-88 ', '61-99 ', '74-85 ',
       '48-89 ', '64-122 ', '42-68 ', '53-106 ', '46-84 ', '80-102 ',
       '50-78 ', '72-128 ', '67-68 ', '69-114 ', '61-103 '], dtype=object)

In [6]:
df['min_salary'] = salary.apply(lambda x: int(x.split('-')[0]))
df['max_salary'] = salary.apply(lambda x: int(x.split('-')[1]))
df['avg_salary'] = (df['min_salary']+df['max_salary'])/2
df.head(1)

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,min_salary,max_salary,avg_salary
0,Business Systems Analyst,$39K-$77K (Glassdoor est.),***This position is eligible for 100% work fro...,3.2,Healthesystems\n3.2,United States,"Tampa, FL",201 to 500 employees,2002,Company - Private,IT Services,Information Technology,$100 to $500 million (USD),"PMSI, myMatrixx",39,77,58.0

## 2. Company Name

In [7]:
df['company_txt'] = df.apply(lambda x: x['Company Name'] if x['Rating'] <0 else x['Company Name'][:-4],axis=1)
df.head(1)

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,min_salary,max_salary,avg_salary,company_txt
0,Business Systems Analyst,$39K-$77K (Glassdoor est.),***This position is eligible for 100% work fro...,3.2,Healthesystems\n3.2,United States,"Tampa, FL",201 to 500 employees,2002,Company - Private,IT Services,Information Technology,$100 to $500 million (USD),"PMSI, myMatrixx",39,77,58.0,Healthesystems

## 3. Location (State)

In [8]:
df['job_state'] = df['Location'].apply(lambda x: x.split(','))
df['job_state'] = df['job_state'].apply(lambda x: x[1] if len(x)==2 else 'na')
df.head(1)

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,min_salary,max_salary,avg_salary,company_txt,job_state
0,Business Systems Analyst,$39K-$77K (Glassdoor est.),***This position is eligible for 100% work fro...,3.2,Healthesystems\n3.2,United States,"Tampa, FL",201 to 500 employees,2002,Company - Private,IT Services,Information Technology,$100 to $500 million (USD),"PMSI, myMatrixx",39,77,58.0,Healthesystems,na

## 4. Is it in the headquarter?

In [9]:
df['is_hq'] = df.apply(lambda x: 1 if x['Headquarters'] == x['Location'] else 0,axis=1)
df.head(1)

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,min_salary,max_salary,avg_salary,company_txt,job_state,is_hq
0,Business Systems Analyst,$39K-$77K (Glassdoor est.),***This position is eligible for 100% work fro...,3.2,Healthesystems\n3.2,United States,"Tampa, FL",201 to 500 employees,2002,Company - Private,IT Services,Information Technology,$100 to $500 million (USD),"PMSI, myMatrixx",39,77,58.0,Healthesystems,na,0

## 5. Age of company

In [10]:
df['Age'] = df['Founded'].apply(lambda x: x if x < 1 else 2020-x)
df.head(2)

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,...,Sector,Revenue,Competitors,min_salary,max_salary,avg_salary,company_txt,job_state,is_hq,Age
0,Business Systems Analyst,$39K-$77K (Glassdoor est.),***This position is eligible for 100% work fro...,3.2,Healthesystems\n3.2,United States,"Tampa, FL",201 to 500 employees,2002,Company - Private,...,Information Technology,$100 to $500 million (USD),"PMSI, myMatrixx",39,77,58.0,Healthesystems,na,0,18
1,Business Systems Analyst,$39K-$77K (Glassdoor est.),Client is seeking Business Systems analysts to...,4.5,Peterson Technology Partners\n4.5,"Northbrook, IL","Park Ridge, IL",201 to 500 employees,1997,Contract,...,Information Technology,$25 to $50 million (USD),-1,39,77,58.0,Peterson Technology Partners,IL,0,23

## 6. Job Desc

In [11]:
#Excel
df['excel'] = df['Job Description'].apply(lambda x: 1 if 'excel' in x.lower() else 0)

#SQL
df['SQL'] = df['Job Description'].apply(lambda x: 1 if 'SQL' in x else 0)

#Python
df['python'] = df['Job Description'].apply(lambda x: 1 if 'python' in x.lower() else 0)

#Tableau
df['tableau'] = df['Job Description'].apply(lambda x: 1 if 'tableau' in x.lower() else 0)

In [12]:
df['excel'].value_counts()

1    676
0    324
Name: excel, dtype: int64

##  7. Simplify Title

In [13]:
df['Job Title'].unique()

array(['Business Systems Analyst', 'Business Analyst',
       'Strategy & Analytics Analyst', 'IT Business Analyst',
       'Fire Business Manager',
       'Business Analyst (2 positions available)',
       'Financial Business Analyst', 'Sales Business Analyst',
       'Business Analyst 1', 'Senior Business Analyst',
       'Business Intelligence Intern', 'Business Analyst – Connectivity',
       'Strategic Business and Requirements Analyst', 'Financial Analyst',
       'Business Analyst II/Sr. Business Analyst',
       'Business Intelligence Analyst', 'Business Intelligence Developer',
       'Customer Solutions Analyst', 'Beer Purchasing Analyst',
       'Product Analyst II', 'Business Analyst I',
       'Customer Insights Sr. Analyst', 'Sales Analyst',
       'Shopper Analyst', 'Business Analyst (IT)', 'Market Analyst',
       'Business Process Analyst - BPA', 'Treasury Analyst',
       'Business Requirement Analyst I', 'Business Analyst I/II',
       'Senior Business Systems Analyst', 'Soapbox Data Analyst',
       'Positions: Business Analyst ID', 'Business Process Analyst',
       'Business Analyst - Independent Contractor',
       'Sr. Analyst, Ops Excellence', 'AVP, Business Intelligence',
       'Privacy Analyst', 'Database Analyst I',
       'Business Intelligence Senior Analyst',
       'Business Strategy Analyst II', 'Equity Research Analyst',
       'Risk Analyst', 'Sr. Business Analyst',
       'CL Associate Operations Analyst', 'Senior Business Analyst IT',
       'Cloud Systems Analyst', 'ERP Systems Analyst',
       'Financial Analyst Part-time',
       'Sr. Marketing Data Analyst (Location Flexible)',
       'Credit Analyst I', 'Professional, Systems Analyst- Revised',
       'Reporting Analyst', 'Senior Business Intelligence Engineer',
       'Associate Analyst', 'Programmer Analyst - Associate',
       'Strategic Sourcing Analyst',
       'Junior Program Analyst (Admin Support)',
       'Business Application Analyst', 'SYSTEM ANALYST II',
       'Enterprise Risk Analyst', 'QA / Business Analyst',
       'CRM System Analyst', 'Senior Business Intelligence Analyst',
       'Business Intelligence Analyst II', 'Credit Analyst',
       'LS Business Analyst', 'Systems Analyst',
       'Customer Insights Analyst', 'Supply Chain Analyst',
       'Lead Business Analyst - STAR', 'Data Quality Analyst',
       'Systems Security Analyst', 'Account Analyst', 'QA Analyst',
       'Business Systems Analyst - SAP PM',
       'Business Intelligence Consultant III - Growing Healthcare Organization',
       'IT Applications - Business Analyst- Reporting',
       'Sr. Strategy and Business Development Analyst', 'Digital Analyst',
       'Business Manager', 'Business Analyst, Strategic Projects Group',
       'BSA/AML Compliance Analyst', 'Default Documents Analyst I',
       'Customer Service Analyst II', 'Director, Business Analytics',
       'Business System Analyst',
       'Business System Analyst, Enterprise Col', 'Senior Analyst',
       'Business Controls Credit Analyst II',
       'Sr. Business Operations Analyst',
       'Principal Analyst, Process and Performance Improvement',
       'Hypersonics Analyst', 'Business Development Analyst',
       'Logistics Analyst - Current Sec+ certification and Active Top Secret or TS/SCI required',
       'Financial Analyst - Bank Admin',
       'Manager, Business Intelligence Business Analyst',
       'Senior Systems Analyst', 'Project Standards Analyst',
       'Business Analyst II- Preventative Maintenance',
       'Application Systems Analyst', 'Business Systems Analyst II',
       'JD Edwards Techno-Functional Analyst',
       'Default Senior Business Analyst', 'Compliance Analyst, Advisory',
       'Product Analyst Intern', 'Quality Analyst II',
       'Cost Analyst, Junior - FAA', 'Integrations Test Analyst',
       'Lead Analyst, Operational Risk', 'Production Control Analyst',
       'SharePoint Systems Analyst',
       'Senior Medical Economics Analyst - Contract Modeling Exp A Plus!',
       'Digital Channel Business Analyst',
       'Product R&D Analyst III/IV - Insurance',
       'Business Continuity Analyst II',
       'Business Analyst II- Manufacturing Operations',
       'SENIOR COST/SCHEDULE ANALYST (COST)',
       'Adobe Analytics Marketing Analyst', 'FP&A Analyst - Commerical',
       'Technical Analyst', 'Applications Systems Analyst',
       'Lead Technical Support Analyst', 'Operations Research Analyst',
       'IT Business Analyst / Finance PM - Temporary', 'Data Analyst II',
       'Senior JDE Business Analyst', 'Project Reporting Analyst',
       'Salesforce Analyst - Posted Internally through Friday, 5/29',
       'Senior Digital Analyst', 'eCommerce Analyst II',
       'Collections Analyst', 'Quality Management Systems Analyst III',
       'Manufacturing Operations Business Analyst - SAP',
       'Transfer Operations Business Analyst', 'Transportation Analyst',
       'Sr Business Data Analyst (Remote)',
       'PeopleSoft Business Analyst III',
       'NPS Business Systems Analyst I - Testing', 'Design Analyst',
       'Market Analyst: Surveillance & Analysis',
       'Bilingual Spanish Credit Analyst', 'Senior Consultant',
       'Business Analyst - Salesforce and Agile Experience Required',
       'Manager Business Intelligence',
       'App Analyst II - Human Resources', 'Operations Process Analyst -',
       'Senior Business System Analyst', 'Digital Risk Analyst II',
       'CDD/EDD/KYC Compliance Analyst', 'Senior Financial Analyst',
       'SR Business Systems Analyst-HRIS',
       'Senior Financial Analyst, Supply Chain', 'SAP FICO Analyst',
       'EDI Analyst III', 'IT Analyst - Governance, Risk & Compliance',
       'Analytics - Business Assurance Data Analyst',
       'Sales Operations Analyst',
       'Commercial Auto Product Analyst - Remote Work from Home Opportunity',
       'Cost Analyst, Mid-Level - DoD',
       'Mid-level All-source Intelligence Analyst AIS',
       'Senior Application Developer and Analyst',
       'Veeva Vault Business Analyst', 'Market Compliance Analyst',
       'EPIC Systems Analyst - Professional Billing',
       'EPIC Systems Analyst - Cadence',
       'Sr. Business Analyst I - Filing Solutions',
       'Sr Systems Analyst Programmer',
       'Senior SAP Functional Analyst in Greensboro, NC at ITG Brands',
       'SENIOR SYSTEMS ANALYST',
       'D365 BC & NAV Senior Functional Consultant',
       'Associate Business Systems Analyst Testing',
       'Cost Estimator/Analyst',
       'Accounting Analyst / Sr. Analyst High Risk Assets Capital Accounts',
       'Intermediate Software Assurance Analyst',
       'Systems Engineer/Analyst', 'Budget Analyst',
       'Global Data Analyst', 'Pricing Analyst', 'Inventory Analyst',
       'Analyst, Enterprise Applications', 'Business Systems Analyst 1',
       'Lead, Business System Analyst', 'Compensation Analyst',
       'Accounting Data and Systems Analyst',
       'Power Systems Operations Business Analyst',
       'Senior Consultant - Project Manager', 'Analyst Compensation',
       'Portfolio Management Analyst I or II',
       'Small Business Consultant - Eastgate FC/Cincinnati OH',
       'Senior IT Business Analyst', 'Finance Business Partner',
       'Jr. Supply Chain Business Analyst',
       'Business Systems Analyst 1 - Future Opportunities',
       'Business Systems Analyst, gRED IT',
       'Help Desk Analyst I, II, III',
       'Business / Data Analyst, Commercial Lines Operations',
       'Project Financial Analyst',
       'Senior Business Analyst / SQL Analyst', 'Product Analyst',
       'Associate Risk Management Analyst',
       'Business Systems Analyst-Chatbot/NLP',
       'Senior Business Systems Analyst, Engineering - Future Consideration',
       'Management Consultant/Sr. Consultant (Life Sciences) NY, NJ and Boston',
       'Senior Analyst, Compensation - Plymouth, MI USA',
       'Analyst I, Actuarial', 'Master Data Operation Analyst',
       'Data Analyst', 'IT Consultants - Business Analysts',
       'Procurement Analyst', 'Compliance Analyst',
       'Director of Business Intelligence',
       'Accounting Analyst I/II/III/Sr.', 'REINSURANCE ANALYST',
       'Supply Chain Analyst - Manufacturing',
       'IT Business Analyst (Supply Chain / Manufacturing)',
       'Senior Strategy Analyst', 'Service Desk Analyst',
       'Acquisition Contracting Analyst', 'Lead Business Analyst',
       'Quality Data Analyst - Clinical Effectiveness (Sepsis) - Full Time',
       'Epic Application Systems Analyst, Specialist - Tapestry',
       'Jr. Business Data Analyst (position added 5/19/2020)',
       'Sr Prov Payment Integ Analyst',
       'Epic Application Systems Analyst, Lead - MyChart',
       'Salesforce Administrator (Systems Business Analyst)',
       'Financial Reporting Analyst', 'Associate Model Office Analyst',
       'Senior Financial Reporting Analyst', 'It Security Analyst',
       'Application Analyst II -QMS',
       'Enterprise Portfolio Management Office Solutions Analyst III',
       'Senior Analyst, Project Assurance', 'QNXT Configuration Analyst',
       'Associate Financial Accounting Analyst',
       'Sales Reporting Analyst',
       'Business Relationship Manager (Analyst, Supply Chain)',
       'Spotfire Reporting Analyst', 'Collateral Analyst',
       'Lead Business Systems Analyst',
       'Senior Business Analyst - Strategic Analytics',
       'International Business Development Analyst, Japan',
       'Benefit Analyst', 'Business Analyst - Lead',
       'Sr. Technical Analyst',
       'Product Analyst - Underwriting Solutions',
       'Senior Staff IT Business Systems Analyst',
       'Private Placement Analyst',
       'Senior IT Business Analyst, IS Projects',
       'Business Development Executive', 'Business Systems Analyst 3',
       'Mid-Level Language Enabled Analyst',
       'Lead IT Business Analyst, IS Projects',
       'Part-Time Analyst, Physical Security',
       'Manager, Business Performance Analytics',
       'Business Manager - The Niello Company', 'BFM Analyst',
       'Oracle AgilePLM Technical Analyst',
       'Financial Application Analyst',
       'Salesforce.com Systems Analyst: Client Services',
       'Clinical R&D Business Analyst',
       'Product Innovation Senior Analyst',
       'Infrastructure Analyst Lead - Specialized IT Services',
       'Business Systems Analyst - Senior',
       'Quality Analyst- Quality Assurance -FT/Days',
       'Business Process Analyst (HR) - Intermediate',
       'Senior Network Fraud Analyst', 'Consumer Lending Data Analyst',
       'D365 BC & NAV Functional Consultant', 'Senior Deal Desk Analyst',
       'Business Intelligence Analyst / Developer III',
       'SAS Programmer Analyst',
       'NAVSEA UWWS Programmatic Support Analyst (Future Opportunity)',
       'D365 F&O Senior Consultant/Architect (Supply Chain)',
       'Senior Consumer Insights Analyst',
       'Electrical Systems Analyst - DODP4', 'IT Security Analyst II',
       'Vendor Performance Analyst II',
       'Business License Associate Analyst', 'Sr Analyst, Strategy',
       'SR IT BUSINESS MGMT ANALYST', 'Jr. Systems Engineer/Analyst',
       'Business Process Analyst - Security+ Certification and Active Top Secret clearance required',
       'Epic Certified Build Analyst',
       'Mortgage Business Systems Analyst',
       'D365 BC & NAV Functional Consultant (with Rental experience)',
       'Sales & Business Development Executive',
       'Senior Analyst, Investor Relations',
       'Medicaid Information and Technology Architecture Analyst',
       'Member Enrollment Analyst', 'NPS Business Systems Analyst',
       'Senior Treasury Analyst', 'Mechanical Systems Analyst - DODP4',
       'Senior Language Enabled Analyst',
       'Network Security Analyst/Engineering Lead',
       'Senior Consultant - Business Performance Analytics',
       'Desktop and Software Support Analyst II',
       'Senior Applications Analyst', 'Credit and Collections Analyst',
       'Senior Accountant and Analyst',
       'Information Security Data Analyst',
       'Enterprise Business Continuity Analyst Senior',
       'Sr. Strategy & Innovation Analyst',
       'D365 BC Senior Functional Consultant (with rental experience)',
       'Project Analyst Per Diem Clinician Directed Performance Improvement',
       'Help Desk Analyst', 'Configuration Analyst',
       'Clinical Systems Analyst',
       'Senior Consultant/Manager - Corporate Banking and Lending Consultant',
       'Senior Digital Marketing Analyst', 'Systems Analyst- JDE World',
       'IT Solutions Senior Consultant',
       'Enterprise Project Management Office (ePMO) Analyst',
       'BI Report Writer - System Analyst',
       'Business Strategy Analyst Senior (Any San Antonio Campus)',
       'Senior Secondary Markets Analyst',
       'Bus Perf Technical/Programmer Analyst-Sign-on Bonus',
       'Telesupervision Board Certified Behavior Analyst - BCBA - Full TIme',
       'Business Analyst JavaScript Developer',
       'Accounting Operations Analyst',
       "Senior Sales Analyst, Walmart & Sam's Club",
       'Business (Commercial) Loan Officer II',
       'Senior Digital Media Forensics Analyst', 'Sr. Pricing Analyst',
       'Salesforce Technical Consultant/Lead',
       'Senior Financial Analyst - Demand',
       'Senior Management Consultant (Cost Modeling SME) CIVP9',
       'Sr. IT Business Analyst, Supply Chain',
       'Report Writer-Data Analyst', 'IT Customer Support Analyst',
       'Senior Transformation Management Consultant',
       'IT Operations System Analyst',
       'Intelligence Policy and Program Analyst IntelP11',
       'Senior Clinical Systems Analyst, Clinical Informatics, Port Angeles, 1.0 FTE, Day Shift',
       'Systems Analyst *MUST HAVE AN ACTIVE SECRET CLEARANCE*',
       'SharePoint Developer (Senior Programmer Analyst)',
       'Senior Consultant - Data Analytics',
       'Senior Consultant – Business Operations', 'Deal Desk Analyst',
       'Kelly: Junior Business Analyst, Computer Assets & Supply Chain at Dow Chemic',
       'Senior Business Continuity Analyst',
       'Business Analyst- Entry Level', 'HRIS Implementation Consultant',
       'Senior HRIS IT Analyst', 'Commodity Manager (Business Analyst)',
       'GRC Analyst', 'Quality Improvement Analyst II',
       'Senior Software Business Analyst',
       'Business Process Analyst , Customer Service & Logistics',
       'IT Business Analyst (Finance)', 'In-Line Inspection Data Analyst',
       'Systems Analyst II',
       'Analyst, Business Intelligence - Publicis Health Media',
       'Partner Business Manager II, Named Account', 'Analyst II',
       'Technical Business Analyst',
       'Management Reporting and Visualization Analyst',
       'Cybercrime Intelligence Analyst - Northern Virginia',
       'Intranet Web Designer & Report Analyst', 'FP&A Analyst',
       'Risk Analyst/Enterprise Risk Management',
       'Business Systems Support Analyst',
       'Business Performance Technical /Programming Analyst Manager',
       'CREDIT ANALYST II',
       'Digital Analytics Analyst - Brand Strategy and Communication',
       'Business Operations Analyst I', 'Transparent.ly Data Analyst',
       'BSS Applications Analyst', 'Retail Commissions Analyst',
       'Senior Product Analyst',
       'Global Sr. Business Systems Analyst (MES)', 'SEO & Web Analyst',
       'Tax Analyst', 'Business Manager - Portland',
       'Business/Data Analyst', 'INFORMATION TECHNOLOGY SECURITY ANALYST',
       'SBA Credit Analyst - Treasure Valley',
       'Business Systems Analyst, Finance AX',
       'Workday - HRIS Business Analyst',
       'Information Security Analyst III',
       'Senior Business Analyst LABS / LIMS / ELN', 'IT Systems Analyst',
       'Analyst, Internal Audit',
       'Compliance Analyst II, Stevens Point, Milwaukee or Green Bay',
       'Sr Analyst II, Purchasing',
       'Senior Compliance and Control Analyst, FEP',
       'Business/Risk Management Analyst',
       'SME Level 1 Digital Media Forensics Analyst',
       'Sourcing Category Management Analyst - MFG - Packaging - Semi-Rigid',
       'Workday Integrations Developer/ Senior Consultant',
       'International Business Development Analyst, Korea',
       'Logistics Analyst (Growler ACQ Support)', 'Naval Project Analyst',
       'Model Office Analyst',
       'Program Analyst (Deputy Operations Officer)',
       'Data Analyst (Secret Clearance Required)',
       'Applications Programmer Analyst',
       'Senior Manager/ Business System Analyst, Supply Chain Systems',
       'Senior Research Analyst', 'Senior Operations Research Analyst',
       'Business Analyst, SmartTrader',
       'Offensive Cyberspace Operations Analyst',
       'Global Sourcing Operations Sr. Analyst',
       'Business Analyst II, Portfolio Communications',
       'Compliance Investment Analyst', 'Foreign Military Sales Analyst',
       'Distribution Operations Analyst',
       'Supply Chain Reporting Analyst',
       'Cybersecurity Governance Analyst',
       'Financial Data Analyst (5am Shift)',
       'Sr Analyst, Strategic Procurement',
       'Management Consultant - Financial Services',
       'Technical Consultant - Transportation',
       'Life Cycle Logistics Management Analyst',
       'Apttus CLM Business Analyst / Configuration Engineer',
       'Data Warehouse Production Support Analyst / Analytic Consultant 3',
       'Subrogation Analyst II', 'Sr. Operations Technical Analyst',
       'Senior HealthCare Analyst', 'Business Analyst, Senior',
       'Business Analyst - Associate', 'Spatial Analyst Product Engineer',
       'Sr Director Platform Business Manager',
       'Financial Analyst, Wholesale Apparel', 'IT VMO Analyst',
       'Lead Shared Risk Financial Analyst',
       'Operations - Quality Analyst',
       'Senior Business Systems Analyst, Lab Information Systems',
       'Sr Analyst, CRM Systems',
       'Senior Systems Analyst, Medication Process',
       'Senior Consultant, Technology Consulting',
       'Sr. Product Analyst / Product Manager',
       'Senior Consultant, Business Solutions',
       'Senior Maximo Business System Analyst',
       'Senior Systems Analyst - Clinical', 'Business Banker IV',
       'Compliance Analyst- Ad Review',
       'Business Analyst - Loan IQ Specialist',
       'Senior Information Security Analyst',
       'Senior Program Compliance / Appeals Analyst',
       'Lead Application Support Analyst', 'Senior IT Projects Analyst',
       'Senior Accountant/Financial Analyst',
       'Product Manager - ArcGIS Business Analyst',
       'Senior Acquisitions Management Analyst',
       'Business Analyst *MUST HAVE AN ACTIVE SECRET CLEARANCE*',
       'Senior Cybersecurity/RMF Analyst',
       'Network Analyst II (Night Operations Support)',
       'Sr. Business Systems Analyst - Regulatory Science, R&D',
       'Board Certified Behavior Analyst (BCBA) - Full Time',
       'Sr ERP Analyst-Customer Service', 'MES IT Analyst',
       'Senior Real Estate Strategy Analyst',
       'Senior User Interface Developer/Senior Consultant',
       'Senior Business Systems Analyst - Manufacturing',
       'Security Systems Analyst',
       'Epic Application Systems Analyst,Sr - Ambulatory/Population Health',
       'ERP Public Sector - Purchasing & Logistics Senior Consultant - Contractor',
       'Financial Analyst CIVP1', 'Business Systems Analyst II - Testing',
       'Sr. CRM Analyst', 'Senior Consultant- Data Analytics',
       'Board Certified Behavior Analyst - BCBA - Full TIme - Phoenix, AZ',
       'CMC Portfolio Analyst in Technical Development',
       'Business/Financial Analyst', 'Lead Data Analyst',
       'Program Financial Analyst', 'IS APPLICATION SUPPORT ANALYST',
       'Technical Business Analyst - Contract Role',
       'Business Analyst - General Liability and Life Insurance',
       'Transformation Management Consultant', 'Surplus Lines Analyst',

In [14]:
def title_simplifier(title):
    if ('business' in title.lower() and 'analyst' in title.lower()) or 'sales' in title.lower() or 'marketing' in title.lower() or 'financial' in title.lower():
        return 'business analyst'
    
    elif 'intelligence' in title.lower():
        return 'business intelligence'
    
    elif 'manager' in title.lower():
        return 'manager'
    
    elif 'analyst' in title.lower():
        return 'analyst'
    
    else:
        return 'na'

In [15]:
df['job_simplified'] = df['Job Title'].apply(title_simplifier)

In [16]:
df['job_simplified'].value_counts()

analyst                  474
business analyst         440
na                        51
manager                   19
business intelligence     16
Name: job_simplified, dtype: int64

# 8. Seniority

In [17]:
def seniority(title):
    if 'sr' in title.lower() or 'senior' in title.lower() or 'lead' in title.lower() or 'principal' in title.lower():
        return 'senior'
    elif 'jr' in title.lower() or 'junior' in title.lower() or 'intern' in title.lower() or 'internship' in title.lower():
        return 'junior'
    else:
        return 'na'

In [18]:
df['seniority'] = df['Job Description'].apply(seniority)
df['seniority'].value_counts()

senior    726
na        148
junior    126
Name: seniority, dtype: int64

# 9. Job desc length

In [19]:
df['desc_len'] = df['Job Description'].apply(lambda x: len(x))
df['desc_len']

0      3022
1      2361
2      3646
3      4427
4      3557
       ...
995    4409
996    6600
997    2733
998    2227
999    4653
Name: desc_len, Length: 1000, dtype: int64

# 10. Competitor count

In [20]:
df['Competitors']

0                                 PMSI, myMatrixx
1                                              -1
2          Subsplash, Ministry Brands, Smartsheet
3                     Union Pacific, BNSF Railway
4                                              -1
                          ...
995                                            -1
996                                            -1
997    Clif Bar, Diamond Foods, Jelly Belly Candy
998                                            -1
999                                            -1
Name: Competitors, Length: 1000, dtype: object

In [21]:
df['competitors_count'] = df['Competitors'].apply(lambda x: len(x.split(',')) if x !='-1' else 0)
df['competitors_count']

0      2
1      0
2      3
3      2
4      0
      ..
995    0
996    0
997    3
998    0
999    0
Name: competitors_count, Length: 1000, dtype: int64

## Save the data

In [29]:
df.to_csv('salary_data_cleaned.csv',index=False)